spring:
  application:
    name: dashboard-collector
  data:
    mongodb:
      uri: mongodb://idashboard:${spring.data.mongodb.credents}@10.120.100.231/idashboard
      credents: ENC(rwQEK1M5vbHwwhhqx6pBDHn4Ut4IrKHbBUsrB0AUR8XHc8GN/Sf4IRVma96OWroe)

jenkins:
  url: "http://10.120.100.231:8888"
  username: "idashboard"
  token : "11a5b80d5d38b6f608951d86cd2966d948"
scheduler:
  cron: 0 0/1 * * * *
  enable: true
server:
  port: 9090
logging:
  level:
    com.cognizant.dashboard.data.collectors.jenkins.clients.JenkinsClient: OFF

  pattern:
    console: '%d{dd-MM-yyyy HH:mm:ss.SSS} %magenta([%thread]) %highlight(%-5level) %logger.%M - %msg%n'

jasypt:
  encryptor:
    algorithm: PBEWITHHMACSHA512ANDAES_256
    password: LeapSecurityKey
