spring:
  application:
    name: CIQDashboard-jenkins-collector
  data:
    mongodb:
      uri:
      credents:
      collection:

jenkins:
  url:
  username:
  token : 

scheduler:
  cron:
  enable:

server:
  port:

logging:
  level:
    com.cognizant.dashboard.data.collectors.jenkins.clients.JenkinsClient:
  pattern:
    console:

jasypt:
  encryptor:
    password:
    bean:
